// src/app/layout.tsx
import type { Metadata } from "next";
import { ThemeProvider } from 'next-themes';

import "./globals.css";
import { Source_Serif_4, Inter, IBM_Plex_Mono } from 'next/font/google';
import Header from "@/components/Header";

const serif = Source_Serif_4({ subsets: ['latin'], variable: '--font-serif' });
const sans = Inter({ subsets: ['latin'], variable: '--font-sans' });
const mono = IBM_Plex_Mono({ subsets: ['latin'], weight: '500', variable: '--font-mono' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${serif.variable} ${sans.variable} ${mono.variable} antialiased bg-[#FAF7F0] dark:bg-[#1B1F1C] text-[#2B2A28] dark:text-[#EDEAE3] min-h-screen`}
      >
        <ThemeProvider attribute='class'>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
